Plonk mixer circuit
webb-tools/arkworks-gadgets pull request #141
Opened 2022-01-21 10:18 UTC by GhostOfGauss

Add the MixerCircuit as described in #121.  

Nothing is being done yet with the arbitrary data.  

Close #121

2022-01-21 10:58 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +	hasher: HG,
This would need to be `HG::Native`, since you would need the composer to make variables with `HG::from_native`

2022-01-21 11:16 UTC, GhostOfGauss commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +	hasher: HG,
good point

2022-01-21 11:23 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +	hasher: HG,
You would have to create a gadget similar to path: https://github.com/webb-tools/arkworks-gadgets/pull/141/files#diff-89b42e9faf445a842b733f0db02bc2912d141c0997e11addc11c2f74477b87d8R68

2022-01-21 12:23 UTC, filiplazovic commented
Looks like we overlooked some things. Namely, adding private inputs. This is done by calling `add_witness_to_circuit_description` (https://github.com/ZK-Garage/plonk/blob/master/plonk-core/src/constraint_system/composer.rs#L175)

Luckily, only PathGadget needs an update. So we just need to add `from_native_witness` or similar, that is the same as the `from_native`, except it calls `add_witness_to_circuit_description` instead of `add_input`.

2022-01-21 21:52 UTC, drewstone requested changes
Looks good so far, I need my memory refreshed on separation between public/private inputs here and whether we should be paying attention to them in the `add_input` API methods. Namely, `nullifier_hash` and `root` are public inputs here and if they are treated differently in the PLONK API such as not needing to be `add_input`'d then we should avoid that in the `fn gadget`.

2022-01-21 21:52 UTC, drewstone commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +		// ? What should be done with arbitrary data ?
We just need to multiply it by itself for the useless constraint. Refer to the comment here: https://github.com/tornadocash/tornado-nova/blob/master/circuits/transaction.circom#L125. We want to achieve the same thing.

2022-01-24 07:49 UTC, GhostOfGauss commented
So piecing together a few conversations with zk garage people:

*   Private inputs like `secret, nullifier` enter the circuit via `composer.add_input`
*   Public inputs like `nullifier_hash` enter the circuit via the `pi` ("public input") field of a gate because this exposes their value to the verifier.  So the verifier knows that the prover did not lie about which `nullifier_hash` he proves pre-image knowledge of.
*   Constants (like poseidon parameters) are where I can't get a straight answer.  It's certainly okay to add these in the `pi` field of a gate but in practice that might be cumbersome.

2022-01-25 08:27 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +			FieldHasherGadget::<F, P>::from_native(composer, self.hasher.clone());
Can we move the hasher below, to separate public inputs and constants.

2022-01-25 08:32 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +			FieldHasherGadget::<F, P>::from_native(composer, self.hasher.clone());
And change the order of public inputs.
1. nullifier_hash
2. root
3. arbitrary_data

This is so we can be consistent with old impl and the pallets. Just to be a little bit more future proof.

2022-01-25 13:33 UTC, GhostOfGauss commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +			FieldHasherGadget::<F, P>::from_native(composer, self.hasher.clone());
Sure thing

2022-01-25 13:38 UTC, filiplazovic approved these changes

2022-01-25 13:54 UTC, merged