Plonk mixer circuit tests
webb-tools/arkworks-gadgets pull request #148
Opened 2022-01-25 14:28 UTC by GhostOfGauss

This adds tests to the mixer circuits.  The discussion of which tests to include begins [here.](https://github.com/webb-tools/arkworks-gadgets/issues/121#issuecomment-1021233993) 

This will close #121 .

2022-01-26 12:05 UTC, filiplazovic commented
Try making helper functions for proving/verifying, to make it easier to review

2022-01-26 16:13 UTC, drewstone commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +	#[should_panic(
I would opt for ensuring errors directly in tests rather than panics here.

2022-01-26 16:15 UTC, drewstone requested changes

2022-01-26 16:15 UTC, drewstone commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +		// // The test will fail due to a TooManyCoefficients error if we use
```suggestion
		// The test will fail due to a TooManyCoefficients error if we use
```

2022-01-26 16:15 UTC, drewstone commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +
Remove new lines

2022-01-26 16:15 UTC, drewstone commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +	#[should_panic(
I would opt for ensuring errors directly in tests rather than panics here.

2022-01-26 16:15 UTC, drewstone commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +
New line should be removed

2022-01-26 16:15 UTC, drewstone commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +	#[should_panic(
I'd recommend verifying errors directly in the test.

`assert_err(..., Error)`

2022-01-26 16:15 UTC, drewstone commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +
New line can be removed

2022-01-26 18:20 UTC, filiplazovic commented on arkworks-plonk-circuits/src/merkle_tree/mod.rs
>  		composer.assert_equal(previous_hash, *root_hash);
These two constraints are the same, why add it?

2022-01-27 12:24 UTC, GhostOfGauss commented on arkworks-plonk-circuits/src/merkle_tree/mod.rs
>  		composer.assert_equal(previous_hash, *root_hash);
Yeah I didn't mean to do that, probably made some kind of merge mistake

2022-01-27 12:42 UTC, GhostOfGauss commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +		for i in 0..(1 << (HEIGHT - 1) - 1) {
done

2022-01-27 12:42 UTC, GhostOfGauss commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +		for i in 0..(1 << (HEIGHT - 1) - 1) {
done

2022-01-27 18:25 UTC, GhostOfGauss commented
All tests are added and working.  I also accounted for some changes that occurred in [this plonk PR](https://github.com/ZK-Garage/plonk/pull/89) that were breaking tests in poseidon and merkle_tree.  

The only thing I have not addressed is @filiplazovic 's suggestion to use a helper function for proving/verifying.  I started doing it and got tripped up by traits.  If you think it's important to do then I can go back and figure that out, though.  Just let me know.

2022-01-27 18:30 UTC, drewstone approved these changes
LGTM, I think helper functions could be made in a separate PR. Will let @filiplazovic decide and merge this.

2022-01-28 09:39 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +		}
This is ok way to populate it. Other options:
1. `[Fq::rand(rng); N]` Although, this will copy the same value `N` times
2. `[(); N].map(|_| F::rand(rng))` Every element will be different

2022-01-28 10:10 UTC, filiplazovic commented on arkworks-plonk-circuits/src/merkle_tree/mod.rs
> +			_ => panic!("Unexpected error"),
```suggestion
			err => panic!("Unexpected error: {:?}", err),
```

2022-01-28 10:10 UTC, filiplazovic commented on arkworks-plonk-circuits/src/merkle_tree/mod.rs
> +			_ => panic!("Unexpected error"),
```suggestion
			err => panic!("Unexpected error: {:?}", err),
```

2022-01-28 10:10 UTC, filiplazovic commented on arkworks-plonk-circuits/src/merkle_tree/mod.rs
> +			_ => panic!("Unexpected error"),
```suggestion
			err => panic!("Unexpected error: {:?}", err),
```

2022-01-28 10:11 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +			_ => panic!("Unexpected error"),
```suggestion
			err => panic!("Unexpected error: {:?}", err),
```

2022-01-28 10:11 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +			_ => panic!("Unexpected error"),
```suggestion
			err => panic!("Unexpected error: {:?}", err),
```

2022-01-28 10:11 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +			_ => panic!("Unexpected error"),
```suggestion
			err => panic!("Unexpected error: {:?}", err),
```

2022-01-28 10:11 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +			_ => panic!("Unexpected error"),
```suggestion
			err => panic!("Unexpected error: {:?}", err),
```

2022-01-28 10:12 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +			_ => panic!("Unexpected error"),
```suggestion
			err => panic!("Unexpected error: {:?}", err),
```

2022-01-28 10:12 UTC, filiplazovic commented on arkworks-plonk-circuits/src/mixer/mod.rs
> +			_ => panic!("Unexpected error"),
```suggestion
			err => panic!("Unexpected error: {:?}", err),
```

2022-01-28 10:47 UTC, filiplazovic approved these changes

2022-01-28 10:50 UTC, merged