First batch of updates
webb-tools/arkworks-gadgets pull request #150
Opened 2022-01-27 12:03 UTC by filiplazovic

2022-01-27 14:30 UTC, filiplazovic commented
@drewstone What else can we include here? It includes mostly info about the mixer. Should we include other circuits?

2022-01-27 14:44 UTC, drewstone commented
I think some notes about the anchors and vanchor is good too.

2022-01-27 21:21 UTC, drewstone requested changes

2022-01-27 21:21 UTC, drewstone commented on README.md
>  Each application-specific file in `src/setup` encapsulates the full-setup of a zero-knowledge gadget's prover and verifier. There are currently application-specific gadgets for:
@filiplazovic this should be fixed to point to the right location.

2022-01-28 12:58 UTC, filiplazovic commented on README.md
> +Utxo is another name for a leaf. VAnchor allows for multiple Utxo's to be deposited or withdrawn in the same transaction.
Still thinking how to explain this better

2022-01-29 23:01 UTC, drewstone commented on README.md
> +Utxo is another name for a leaf. VAnchor allows for multiple Utxo's to be deposited or withdrawn in the same transaction.
UTXOs stand for unspent transaction outputs. Each UTXO represents a shielded balance that can be spent in the system. In order to create new UTXOs one must prove ownership over existing UTXOs that have at least as much balance as the newly created one. 

UTXOs contain a value, denoting the amount contained in the UTXO, the chain ID where the UTXO is meant to be spent on, and secret data relevant for creating zero-knowledge proofs of ownership and membership over.

UTXOs are deposited and stored in on-chain merkle trees first by serializing its components and then by hashing the serialized data before insertion. Each hash can be considered a commitment to a UTXO. In order to create new UTXOs from old ones, users must submit valid zero-knowledge proofs that satisfy constraints around the consistency of values and membership within a set of merkle roots.

2022-01-29 23:02 UTC, drewstone commented on README.md
> +Utxo is another name for a leaf. VAnchor allows for multiple Utxo's to be deposited or withdrawn in the same transaction.
Let me know what you think @filiplazovic

2022-01-31 09:11 UTC, filiplazovic commented on README.md
> +Utxo is another name for a leaf. VAnchor allows for multiple Utxo's to be deposited or withdrawn in the same transaction.
This is really good

2022-01-31 16:26 UTC, merged