return structs instead of tuples
webb-tools/arkworks-gadgets pull request #155
Opened 2022-01-30 14:45 UTC by OAyomide

2022-01-31 21:36 UTC, filiplazovic commented on arkworks-circuits/src/setup/anchor.rs
> +pub struct Leaf_x5_4 {
Lets ditch the `_x5_4` suffix. This struct should be the same for different Poseidon configurations

2022-01-31 21:37 UTC, filiplazovic commented on arkworks-circuits/src/setup/anchor.rs
> +pub struct Leaf_x5_4 {
This applies to every struct (both Mixer and Anchor)

2022-01-31 22:05 UTC, filiplazovic commented on arkworks-circuits/src/setup/anchor.rs
> +	vk: Vec<u8>,
Lets also make all fields public, in all structs added

2022-02-01 17:30 UTC, OAyomide commented on arkworks-circuits/src/setup/anchor.rs
> +pub struct Leaf_x5_4 {
i am not sure what you mean by "different poseidon configurations"

2022-02-01 17:40 UTC, OAyomide commented on arkworks-circuits/src/setup/anchor.rs
> +pub struct Leaf_x5_4 {
also i am not sure what to name the structs. i am thinking of pretending "Poseidon" to the structs name, for example `Leaf_x5_4` would be `PoseidonLeaf`

the reason is because it seems to be consistent with the naming as far as i can tell. is this a deal breaker?

2022-02-01 18:36 UTC, filiplazovic commented on arkworks-circuits/src/setup/anchor.rs
> +pub struct Leaf_x5_4 {
`x5` stands for exponentiation 5 for poseidon sbox, and `4` is the width of the inputs passed into the poseidon hash function. Since this struct hold the bytes representation, it wont change if the exponentiation/width is changed.

`PoseidonLeaf` is also an option, but just `Leaf` is enough

2022-02-03 12:25 UTC, filiplazovic commented
This looks good. Can you run `cargo fmt` @OAyomide and push the changes, before we can merge

2022-02-03 13:18 UTC, filiplazovic commented
I changed the base `OAyomide/return-structs-not-tuples` so that we can run CI, before merging to master

2022-02-03 15:13 UTC, drewstone commented on arkworks-circuits/src/setup/anchor.rs
> +	Ok(LeafWithPrivateRaw {
We can just return the full `Leaf` here as you are doing above.

2022-02-03 15:13 UTC, drewstone commented on arkworks-circuits/src/setup/common.rs
> +pub struct LeafWithPrivateRaw {
We don't need this since we can reuse the Leaf

2022-02-03 15:13 UTC, drewstone commented on arkworks-circuits/src/setup/mixer.rs
> +	Ok(LeafWithPrivateRaw {
Here too, we should use the `Leaf` and add to the secret and nullifier bytes

2022-02-03 15:14 UTC, drewstone requested changes
LGTM once the last changes land this is good and we can update the `wasm-utils` side.

2022-02-04 15:36 UTC, filiplazovic commented on arkworks-circuits/src/setup/anchor.rs
> +		nullifier_bytes: vec![],
This should return [nullifier bytes](https://github.com/webb-tools/arkworks-gadgets/pull/155/files#diff-4514b356dea78f6184c1ea3c1ecfeb40620eb670289f08809a33f90367c7a8bbR86) (and you can also fix the spelling mistake)

2022-02-10 01:28 UTC, OAyomide commented
@filiplazovic (review please)

2022-02-10 09:42 UTC, filiplazovic commented
Thanks for the PR @OAyomide

2022-02-10 09:42 UTC, merged