Filip/update readme 2
webb-tools/arkworks-gadgets pull request #202
Opened 2022-03-20 13:50 UTC by filiplazovic

2022-03-20 15:07 UTC, drewstone requested changes
Looks good. Left some comments. Can we include links to the relayer repo as well? Are there scripts we can also link for generating trusted setup parameters for plonk and R1CS for these circuits? I think that would be helpful to have here.

2022-03-20 15:07 UTC, drewstone commented on README.md
> +Anchor protocol is very similar to the mixer. Instead of proving the membership inside one Merkle tree, we are proving the membership in many Merkle trees. These trees can live on many different bloc
Proving inclusion in one of many

2022-03-20 15:07 UTC, drewstone commented on README.md
> +1. We are computing the leaf commitment using the Poseidon hash function passing: `secret` (private input), `nullifier` (private input).
Shouldn't this include the chain Id for the anchor leaf hash computation too?

2022-03-21 10:25 UTC, filiplazovic commented
Fixed. There is also a task for trusted setups, which has much more context: https://github.com/webb-tools/arkworks-gadgets/issues/78

2022-03-21 11:21 UTC, merged