Dami/hex no std
webb-tools/arkworks-gadgets pull request #213
Opened 2022-05-12 16:46 UTC by dharjeezy

The protocol-ink poseidon contract could not compile successfully due to std feature issues. This is a slight change to enable the poseidon contract compile successfully.

2022-05-12 16:54 UTC, shekohex requested changes
Looks good.

A few more small changes, before we can merge this.

2022-05-12 16:54 UTC, shekohex commented on arkworks-gadgets.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Please add this file to .gitignore.

2022-05-12 16:54 UTC, shekohex commented on arkworks-utils/Cargo.toml
> +hex = {version = "0.4", default-features = false}
```suggestion
hex = { version = "0.4", default-features = false }
```

2022-05-12 16:54 UTC, shekohex commented on arkworks-utils/src/lib.rs
> +	Ok(bytes.to_vec())
```suggestion
	Ok(bytes.into())
```

2022-05-12 18:54 UTC, dharjeezy commented on arkworks-gadgets.iml
> +<?xml version="1.0" encoding="UTF-8"?>
I have added it

2022-05-12 19:18 UTC, shekohex commented on arkworks-gadgets.iml
> +<?xml version="1.0" encoding="UTF-8"?>
But it is still there, try using `git rm --cache arkworks-gadgets.iml` for example.

2022-05-13 20:04 UTC, dharjeezy commented on arkworks-gadgets.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Done.

2022-05-16 11:37 UTC, drewstone commented
Tests and CI need to be updated/fixed @dharjeezy

2022-05-16 15:03 UTC, dharjeezy commented
Closing this because it has old commits. New PR here https://github.com/webb-tools/arkworks-gadgets/pull/216

2022-05-16 15:03 UTC, closed without merging