Adding the new leaf structure(not Completed yet)
webb-tools/arkworks-gadgets pull request #47
Opened 2021-11-01 15:09 UTC by mfaghihi

Structure for the new leaf. (Not done yet)

2021-11-01 15:33 UTC, drewstone requested changes

2021-11-01 15:33 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +	r: FpVar<F>,
We don't need this parameter
```suggestion
```

2021-11-01 15:33 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +	nullifier: FpVar<F>,
We don't need this parameter either
```suggestion
```

2021-11-01 15:33 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +	fn create_nullifier(
We'll need to update this with the new nullifier structure.

2021-11-01 17:54 UTC, filiplazovic commented on src/leaf/newleaf/mod.rs
> +		let bytes = to_bytes![c, s.priv_key, s.merkle_path]?;
@drewstone Why is `merkle_path` inside a nullifier.

It looks like it doesn't make sense to have `create_nullifier_hash` be part of the leaf gadget

2021-11-01 18:04 UTC, filiplazovic commented on src/leaf/newleaf/mod.rs
> +		let bytes = to_bytes![c, s.priv_key, s.merkle_path]?;
Or it could be passed as an argument for now

2021-11-01 18:27 UTC, drewstone commented on src/leaf/newleaf/mod.rs
> +		let bytes = to_bytes![c, s.priv_key, s.merkle_path]?;
Yea it should be passed in as a function parameter. Also it's not the merkle path but the index of the leaf in the tree @mfaghihi. Please check on the structure in the solidity repo.

2021-11-01 18:28 UTC, drewstone commented on src/leaf/newleaf/mod.rs
> +		let bytes = to_bytes![c, s.priv_key, s.merkle_path]?;
https://github.com/webb-tools/protocol-solidity/blob/akilesh-tornPoolCircuits/circuits/vbridge/transaction.circom#L18

2021-11-01 21:01 UTC, filiplazovic commented on src/leaf/constraints.rs
> +pub trait NewLeafCreationGadget<F: Field, H1: CRH, HG1: CRHGadget<H1, F>, L: NewLeafCreation<H1>>:
Not sure if creating a new Trait is a good idea since the old one is already used here:
https://github.com/webb-tools/arkworks-gadgets/blob/master/src/circuit/bridge.rs#L31

2021-11-01 21:12 UTC, mfaghihi commented on src/leaf/constraints.rs
> +pub trait NewLeafCreationGadget<F: Field, H1: CRH, HG1: CRHGadget<H1, F>, L: NewLeafCreation<H1>>:
You are right, I made this one temporarily.  In the final version, only one trait will remain for this purpose.

2021-11-02 17:47 UTC, drewstone requested changes

2021-11-02 17:47 UTC, drewstone commented on src/leaf/constraints.rs
> +		indices: &Vec<UInt8<F>>,
```suggestion
		indices: &FpVar,
```

2021-11-02 17:47 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +		 // TODO: extend to all indices
```suggestion
```
Do we need this comment?

2021-11-02 17:47 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +		indices: &Vec<UInt8<F>>,
```suggestion
		indices: &FpVar,
```

2021-11-02 17:47 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +		bytes.extend(indices.to_bytes()?);
the ordering in the solidity is `[commitment, index, privkey]`

https://github.com/webb-tools/protocol-solidity/blob/akilesh-tornPoolCircuits/lib/vbridge/utxo.ts#L61

2021-11-02 17:47 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +		let indice_var=UInt8::new_witness(cs.clone(), || {	Ok(indices[0])
This isn't quite correct. Just use an `FpVar`, we'll have to do bit decomposition and composition in circuit.

2021-11-02 19:28 UTC, drewstone commented on src/leaf/mod.rs
> +	fn create_nullifier_hash<F: PrimeField>(
```suggestion
	fn create_nullifier<F: PrimeField>(
```

2021-11-02 19:30 UTC, drewstone requested changes
Change `create_nullifier_hash` to `create_nullifier` so that the native and constraint gadget match. Some spacing issues still and also please compile on nightly since that is where this code will be used downstream.

2021-11-02 19:30 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +		let indice_var=FpVar::new_witness(cs.clone(), || {	Ok(index)
spacing is still off here @mfaghihi, please fix.

2021-11-02 20:48 UTC, mfaghihi commented on rust-toolchain.toml
> +channel = "stable"
please check the nightly version. I used a newer one.

2021-11-03 08:40 UTC, filiplazovic commented on src/leaf/newleaf/mod.rs
> +	index: F,
Index shouldn't be a part of Private, since we don't have it when its constructed, same goes for PrivateVar

2021-11-03 08:46 UTC, filiplazovic commented on src/leaf/newleaf/constraints.rs
> +}
These are already implemented inside the AllocVar trait in exact same way

2021-11-03 14:32 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +	index: FpVar<F>,
this should not be here

2021-11-04 17:10 UTC, drewstone requested changes
Last remaining fix before this looks good to go.

2021-11-04 17:10 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +	pubkey: FpVar<F>,
So as per the circuit impl in circom, we don't pass the pubkey into either variable. Instead, we compute it as the poseidon hash of the private key
```
template Keypair() {
    signal input privateKey;
    signal output publicKey;

    component hasher = Poseidon(1);
    hasher.inputs[0] <== privateKey;
    publicKey <== hasher.out;
}
```

2021-11-04 17:10 UTC, drewstone commented on src/leaf/newleaf/constraints.rs
> +	pubkey: FpVar<F>,
This means we would need to pass in the Poseidon gadget to this gadget to also compute the pubkey hash on the fly, when we have access to the private key.

2021-11-04 21:13 UTC, merged