Hossein.vanchor
webb-tools/arkworks-gadgets pull request #48
Opened 2021-11-04 22:22 UTC by mfaghihi

A simple gadget for keypairs is made. 
vanchor.rs is mostly a copy of bridge circuit. But it needs major changes. specially, I couldn't use the private key inside the generate_constraints function to compute the public key

2021-11-05 21:12 UTC, drewstone requested changes
Request to change anything `Keypairs` to `Keypair` including fiie names.

2021-11-05 21:12 UTC, drewstone commented on src/circuit/vanchor/constraints.rs
> +pub struct KeypairsVar<
Can we call this `KeypairVar` instead? I don't see why we would use plurals here.

2021-11-05 21:12 UTC, drewstone commented on src/circuit/vanchor/constraints.rs
> +pub trait KeypairsCreationGadget<H: CRH, HG: CRHGadget<H, F>, F: PrimeField, L: NewLeafCreation<H>, LG: NewLeafCreationGadget<F, H, HG, L>>: Sized {
`KeypairCreationGadget`

2021-11-05 21:30 UTC, drewstone requested changes
Will hold off too many comments while this is still WIP. Can we change the `newleaf` file names to be indexed under `leaf/vanchor`, `newleaf` is not a very good name.

2021-11-05 21:30 UTC, drewstone commented on src/circuit/vanchor/transaction.rs
> +	outChaiID: Vec<F>,
```suggestion
	outChainID: Vec<F>,
```

2021-11-05 21:30 UTC, drewstone commented on src/circuit/vanchor/transaction.rs
> +	publicAmount: Vec<F>,
```suggestion
	publicAmount: F,
```

2021-11-05 21:30 UTC, drewstone commented on src/circuit/vanchor/transaction.rs
> +	extDataHash: Vec<A>,
```suggestion
	extDataHash: F,
```

2021-11-05 21:30 UTC, drewstone commented on src/circuit/vanchor/transaction.rs
> +	extDataHash: Vec<A>,
the ext data hash is a hash of data giving us a field element

2021-11-05 21:30 UTC, drewstone commented on src/circuit/vanchor/transaction.rs
> +	publicAmount: Vec<F>,
Public amount is just public field element

2021-11-05 21:30 UTC, drewstone commented on src/circuit/vanchor/transaction.rs
> +	inKeyPair: Vec<F>,
How is `inKeyPair` different from `inPrivateKey`?

2021-11-05 21:30 UTC, drewstone commented on src/circuit/vanchor/transaction.rs
> +	inUtxoHasher: H,
this should basically be the leaf hasher, so we can remove

2021-11-05 21:30 UTC, drewstone commented on src/circuit/vanchor/transaction.rs
> +	nullifierHasher: H,
this should basically be the same as the leaf hasher with different # of inputs, so not needed, otherwise I would creaet a nullifier gadget and we should follow the structure we have here w/ a `_nullifier_hasher_gadget`

2021-11-05 21:30 UTC, drewstone commented on src/circuit/vanchor/vanchor.rs
> +	root: <C::H as CRH>::Output,
This should be removed, we only rely on root set.

2021-11-05 21:30 UTC, drewstone commented on src/circuit/vanchor/vanchor.rs
> +			root,
This should be removed, we only rely on root set.

2021-11-08 13:25 UTC, filiplazovic commented on src/circuit/vanchor/transaction.rs
> +	}
This could be a part of the circuit impl.
Alternatively, if we want to keep it as a gadget, it should be in its own separate folder.
Thoughts?

2021-11-08 13:57 UTC, filiplazovic commented on src/leaf/vanchor/constraints.rs
> +	pub priv_key: FpVar<F>,
Why not hash it inside `create_leaf`, instead of taking it out, hashing it, and passing it to the nullifier function.
Then there is no need for Keypair and the interface is simpler.

Or maybe I'm missing something?

2021-11-10 10:17 UTC, filiplazovic commented on src/circuit/vanchor.rs
> +		leaf_public_var: &LG::PublicVar, //TODO: this doesn't need to be Vec
I think it does need to be a vector. Every leaf can potentially have different chain_id

2021-11-10 14:05 UTC, drewstone commented on src/circuit/vanchor.rs
> +		leaf_public_var: &LG::PublicVar, //TODO: this doesn't need to be Vec
Every input lead being spent actually using the same chain ID, that of the chain they're transacting on. This is the public chain ID passed into the circuit. 

The output commitments are what can have any chain ID.

2021-11-10 14:48 UTC, filiplazovic commented on src/circuit/vanchor.rs
> +		leaf_public_var: &LG::PublicVar, //TODO: this doesn't need to be Vec
Yeah, right. The verification will fail if the chain_id is invalid, we don't need to check it explicitly

2021-11-10 14:50 UTC, mfaghihi commented on src/circuit/vanchor.rs
> +			).unwrap();
You are right. I did it, but not pushed it yet

2021-11-10 15:09 UTC, drewstone commented on src/circuit/vanchor.rs
> +			in_amounttx = LG::get_amount(&leaf_private_var[tx]).unwrap();
```suggestion
			in_amount_tx = LG::get_amount(&leaf_private_var[tx]).unwrap();
```

2021-11-10 17:59 UTC, mfaghihi commented on src/circuit/vanchor.rs
>  		// End of  TENTATIVE CODE
I'm not sure if the code in lines 340-345 is doing the job correctly, so I wrote the tentative one as well. If you think the first one should be enough, we can remove the TENTATIVE one. Also, the TENTATIVE one can be more succinct.

2021-11-12 14:06 UTC, filiplazovic commented on src/set/membership/constraints.rs
> +	fn membership_success_not_eanbled() {
```suggestion
	fn membership_success_not_enabled() {
```

2021-11-16 22:16 UTC, merged