reorganizing the repo
webb-tools/arkworks-gadgets pull request #59
Opened 2021-11-27 00:23 UTC by mfaghihi

doesn't compile yet. needs to add scripts and fix errors

2021-11-27 15:29 UTC, drewstone requested changes
Build and CI is failing.

2021-11-29 19:09 UTC, filiplazovic commented on arkworks-benchmarks/Cargo.toml
> +std = ["ark-std/std"]
We don't need these features in benchmarks

2021-11-29 19:10 UTC, filiplazovic commented on arkworks-benchmarks/Cargo.toml
> +required-features = ["r1cs", "std", "default_poseidon", "test"]
We may not need this. Lets make it a binary, for simplicity

2021-11-29 19:11 UTC, filiplazovic commented on arkworks-benchmarks/Cargo.toml
> +std = ["ark-std/std"]
And check other crates too

2021-11-30 14:29 UTC, filiplazovic commented on arkworks-benchmarks/Cargo.toml
> +std = ["ark-std/std"]
Please check other crates. Only `arkworks-utils` need these features

2021-11-30 18:05 UTC, filiplazovic approved these changes

2021-11-30 18:31 UTC, merged